permalink: /:categories/:title.html
url: "https://primalinstinct.github.io/"
full_name: "Fount of Creativity"
first_name: "Primal"
last_name: "Instinct"
blog_title: "Fount of Creativity | Your Source of Fascinating Facts"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: ""
copyright_year: "2020"
google_analytics_code: ""
aboutme: "Something about the author here"
twitter: ""
github: "PrimalInstinct"
facebook: ""
linkined_url: ""
